### ISSUE TITLE
switch example

### ISSUE THREAD

**Issue by slawern** [povilasb/style-guides#1]
The switch example reads:

switch (http_method) {
HTTP_GET:
        break;

HTTP_POST:
        breaj;

default:
}

while it should read:

switch (http_method) {
case HTTP_GET:
        break;

case HTTP_POST:
        break;

default:
}

**Comment by povilasb** [comment]
Thanks, I updated it: https://github.com/povilasb/style-guides/commit/89abac2e6df5634740abfd1cc2d6b75406c3b321 ;)
